<?php

use Faker\Generator as Faker;

$factory->define(App\CPRFormat::class, function (Faker $faker) {
    return [

      'patient_name'=> $faker->word,
      'ipd_no'=> $faker->word,
      'age'=> $faker->word,
      'sex'=> $faker->word,
      'date'=> $faker->date,
      'start_time'=> $faker->time,
      'bed_no'=> $faker->word,
      'diagnosis'=> $faker->word,
      'name_doctor'=> $faker->word,
      'cpr_team'=> $faker->word,
      'intubation_time'=> $faker->time,
      'defib_rhythm_00'=> $faker->word,
      'defib_rhythm_01'=> $faker->word,
      'defib_rhythm_02'=> $faker->word,
      'defib_rhythm_03'=> $faker->word,
      'defib_rhythm_04'=> $faker->word,
      'defib_dc_00'=> $faker->word,
      'defib_dc_01'=> $faker->word,
      'defib_dc_02'=> $faker->word,
      'defib_dc_03'=> $faker->word,
      'defib_dc_04'=> $faker->word,
      'medication_time_00'=> $faker->time,
      'medication_name_01'=> $faker->word,
      'medication_time_10'=> $faker->time,
      'medication_name_11'=> $faker->word,
      'medication_time_20'=> $faker->time,
      'medication_name_21'=> $faker->word,
      'medication_time_30'=> $faker->time,
      'medication_name_31'=> $faker->word,
      'medication_time_40'=> $faker->time,
      'medication_name_41'=> $faker->word,
      'total_time'=> $faker->time,
      'outcome'=> $faker->word,
      'doctor_name'=> $faker->word,
      'remarks'=> $faker->word,
      'consultant_counseled'=> $faker->word,
      'relative_name'=> $faker->word,
      'initial_time'=>$faker->time,
      '_00_01'=> $faker->word,
      '_00_02'=> $faker->word,
      '_00_03'=> $faker->word,
      '_00_04'=> $faker->word,
      '_00_05'=> $faker->word,
      '_00_06'=> $faker->word,
      '_00_07'=> $faker->word,
      '_00_08'=> $faker->word,
      '_01_01'=> $faker->word,
      '_01_02'=> $faker->word,
      '_01_03'=> $faker->word,
      '_01_04'=> $faker->word,
      '_01_05'=> $faker->word,
      '_01_06'=> $faker->word,
      '_01_07'=> $faker->word,
      '_01_08'=> $faker->word,
      '_02_01'=> $faker->word,
      '_02_02'=> $faker->word,
      '_02_03'=> $faker->word,
      '_02_04'=> $faker->word,
      '_02_05'=> $faker->word,
      '_02_06'=> $faker->word,
      '_02_07'=> $faker->word,
      '_02_08'=> $faker->word,
      '_03_01'=> $faker->word,
      '_03_02'=> $faker->word,
      '_03_03'=> $faker->word,
      '_03_04'=> $faker->word,
      '_03_05'=> $faker->word,
      '_03_06'=> $faker->word,
      '_03_07'=> $faker->word,
      '_03_08'=> $faker->word,
      '_04_01'=> $faker->word,
      '_04_02'=> $faker->word,
      '_04_03'=> $faker->word,
      '_04_04'=> $faker->word,
      '_04_05'=> $faker->word,
      '_04_06'=> $faker->word,
      '_04_07'=> $faker->word,
      '_04_08'=> $faker->word,
      '_05_01'=> $faker->word,
      '_05_02'=> $faker->word,
      '_05_03'=> $faker->word,
      '_05_04'=> $faker->word,
      '_05_05'=> $faker->word,
      '_05_06'=> $faker->word,
      '_05_07'=> $faker->word,
      '_05_08'=> $faker->word,
      '_06_01'=> $faker->word,
      '_06_02'=> $faker->word,
      '_06_03'=> $faker->word,
      '_06_04'=> $faker->word,
      '_06_05'=> $faker->word,
      '_06_06'=> $faker->word,
      '_06_07'=> $faker->word,
      '_06_08'=> $faker->word,
      'initial_time'=>$faker->time
    ];


});
