<?php

use Faker\Generator as Faker;

$factory->define(App\DrugRequisition::class, function (Faker $faker) {
    return [
        //
        'name_of_drug_01' => $faker->word,
        'quantity_01' => $faker->word,
        'batch_no_01' => $faker->word,
        'expiry_date_01' => $faker->date,
        'issued_by_01' => $faker->word,
        'received_by_01' => $faker->word,
        'name_of_drug_02' => $faker->word,
        'quantity_02' => $faker->word,
        'batch_no_02' => $faker->word,
        'expiry_date_02' => $faker->date,
        'issued_by_02' => $faker->word,
        'received_by_02' => $faker->word,
        'name_of_drug_03' => $faker->word,
        'quantity_03' => $faker->word,
        'batch_no_03' => $faker->word,
        'expiry_date_03' => $faker->date,
        'issued_by_03' => $faker->word,
        'received_by_03' => $faker->word,
        'name_of_drug_04' => $faker->word,
        'quantity_04' => $faker->word,
        'batch_no_04' => $faker->word,
        'expiry_date_04' => $faker->date,
        'issued_by_04' => $faker->word,
        'received_by_04' => $faker->word,
        'name_of_drug_05' => $faker->word,
        'quantity_05' => $faker->word,
        'batch_no_05' => $faker->word,
        'expiry_date_05' => $faker->date,
        'issued_by_05' => $faker->word,
        'received_by_05' => $faker->word,
        'name_of_drug_06' => $faker->word,
        'quantity_06' => $faker->word,
        'batch_no_06' => $faker->word,
        'expiry_date_06' => $faker->date,
        'issued_by_06' => $faker->word,
        'received_by_06' => $faker->word,
        'name_of_drug_07' => $faker->word,
        'quantity_07' => $faker->word,
        'batch_no_07' => $faker->word,
        'expiry_date_07' => $faker->date,
        'issued_by_07' => $faker->word,
        'received_by_07' => $faker->word,
        'name' => $faker->word,
        'date' => $faker->date,
        'time' => $faker->time,
    ];
});
