<?php

use Faker\Generator as Faker;

$factory->define(App\ERObservation::class, function (Faker $faker) {
    return [
      'date' => $faker->date,
      'triage_category' => $faker->word,
      'diagnosis' => $faker->word,
      'investigation' => $faker->word,
      'time_01' => $faker->time,
      'time_02' => $faker->time,
      'time_03' => $faker->time,
      'pulse_01' => $faker->word,
      'pulse_02' => $faker->word,
      'pulse_03' => $faker->word,
      'bp_01' => $faker->word,
      'bp_02' => $faker->word,
      'bp_03' => $faker->word,
      'spo2_01' => $faker->word,
      'spo2_02' => $faker->word,
      'spo2_03' => $faker->word,
      'rr_01' => $faker->word,
      'rr_02' => $faker->word,
      'rr_03' => $faker->word,
      'gcs_01' => $faker->word,
      'gcs_02' => $faker->word,
      'gcs_03' => $faker->word,
      'temp_01' => $faker->word,
      'temp_02' => $faker->word,
      'temp_03' => $faker->word,
      'iv_infusion_01' => $faker->word,
      'qty_01' => $faker->word,
      'time_start_01' => $faker->time,
      'time_end_01' => $faker->time,
      'remarks_01' => $faker->word,
      'iv_infusion_02' => $faker->word,
      'qty_02' => $faker->word,
      'time_start_02' => $faker->time,
      'time_end_02' => $faker->time,
      'remarks_02' => $faker->time,
      'iv_infusion_03' => $faker->word,
      'qty_03' => $faker->word,
      'time_start_03' => $faker->time,
      'time_end_03' => $faker->time,
      'remarks_03' => $faker->word,
      'iv_infusion_04' => $faker->word,
      'qty_04' => $faker->word,
      'time_start_04' => $faker->time,
      'time_end_04' => $faker->time,
      'remarks_04' => $faker->word,
      'name_drug_01' => $faker->word,
      'dosage_01' => $faker->word,
      'routine_01' => $faker->word,
      'administration_by_01' => $faker->word,
      'medication_time_01' => $faker->time,
      'name_drug_02' => $faker->word,
      'dosage_02' => $faker->word,
      'routine_02' => $faker->word,
      'administration_by_02' => $faker->word,
      'medication_time_02' => $faker->time,
      'name_drug_03' => $faker->word,
      'dosage_03' => $faker->word,
      'routine_03' => $faker->word,
      'administration_by_03' => $faker->word,
      'medication_time_03' => $faker->time,
      'name_drug_04' => $faker->word,
      'dosage_04' => $faker->word,
      'routine_04' => $faker->word,
      'administration_by_04' => $faker->word,
      'medication_time_04' => $faker->time,
      'name_drug_05' => $faker->word,
      'dosage_05' => $faker->word,
      'routine_05' => $faker->word,
      'administration_by_05' => $faker->word,
      'medication_time_05' => $faker->time,
      'patient_shifted_to' => $faker->word,
      'er_nurse' => $faker->word,
    ];
});
