<?php

use Faker\Generator as Faker;

$factory->define(App\NurseProgressNotes::class, function (Faker $faker) {
    return [
      'date_00'=>$faker->date,
      'time_00'=>$faker->time,
      'progress_00'=> $faker->word,
      'staff_name_00'=> $faker->word,
      'sign_00'=> $faker->word,
      'date_01'=>$faker->date,
      'time_01'=>$faker->time,
      'progress_01'=> $faker->word,
      'staff_name_01'=> $faker->word,
      'sign_01'=> $faker->word,
      'date_02'=>$faker->date,
      'time_02'=>$faker->time,
      'progress_02'=> $faker->word,
      'staff_name_02'=> $faker->word,
      'sign_02'=> $faker->word,
      'date_03'=>$faker->date,
      'time_03'=>$faker->time,
      'progress_03'=> $faker->word,
      'staff_name_03'=> $faker->word,
      'sign_03'=> $faker->word,
      'date_04'=>$faker->date,
      'time_04'=>$faker->time,
      'progress_04'=> $faker->word,
      'staff_name_04'=> $faker->word,
      'sign_04'=> $faker->word,
      'date_05'=>$faker->date,
      'time_05'=>$faker->time,
      'progress_05'=> $faker->word,
      'staff_name_05'=> $faker->word,
      'sign_05'=> $faker->word,
      'date_06'=>$faker->date,
      'time_06'=>$faker->time,
      'progress_06'=> $faker->word,
      'staff_name_06'=> $faker->word,
      'sign_06'=> $faker->word,
      'date_07'=>$faker->date,
      'time_07'=>$faker->time,
      'progress_07'=> $faker->word,
      'staff_name_07'=> $faker->word,
      'sign_07'=> $faker->word,
      'date_08'=>$faker->date,
      'time_08'=>$faker->time,
      'progress_08'=> $faker->word,
      'staff_name_08'=> $faker->word,
      'sign_08'=> $faker->word,
      'date_09'=>$faker->date,
      'time_09'=>$faker->time,
      'progress_09'=> $faker->word,
      'staff_name_09'=> $faker->word,
      'sign_09'=> $faker->word,
      'date_10'=>$faker->date,
      'time_10'=>$faker->time,
      'progress_10'=> $faker->word,
      'staff_name_10'=> $faker->word,
      'sign_10'=> $faker->word,

    ];
});
