<?php

use Faker\Generator as Faker;

$factory->define(App\NurseProgressNotes::class, function (Faker $faker) {
    return [
      'date_00'=>$faker->date,
      'time_00'=>$faker->time,
      'progress_00'=> $faker->word,
      'staff_name_00'=> $faker->word,
      'sign_00'=> $faker->word,
      'date_01'=>$faker->date,
      'time_01'=>$faker->time,
      'progress_01'=> $faker->word,
      'staff_name_01'=> $faker->word,
      'sign_01'=> $faker->word,
      'date_02'=>$faker->date,
      'time_02'=>$faker->time,
      'progress_02'=> $faker->word,
      'staff_name_02'=> $faker->word,
      'sign_02'=> $faker->word,
      'date_03'=>$faker->date,
      'time_03'=>$faker->time,
      'progress_03'=> $faker->word,
      'staff_name_03'=> $faker->word,
      'sign_03'=> $faker->word,
      'date_04'=>$faker->date,
      'time_04'=>$faker->time,
      'progress_04'=> $faker->word,
      'staff_name_04'=> $faker->word,
      'sign_04'=> $faker->word,
      'date_05'=>$faker->date,
      'time_05'=>$faker->time,
      'progress_05'=> $faker->word,
      'staff_name_05'=> $faker->word,
      'sign_05'=> $faker->word,
      'date_06'=>$faker->date,
      'time_06'=>$faker->time,
      'progress_06'=> $faker->word,
      'staff_name_06'=> $faker->word,
      'sign_06'=> $faker->word,
      'date_07'=>$faker->date,
      'time_07'=>$faker->time,
      'progress_07'=> $faker->word,
      'staff_name_07'=> $faker->word,
      'sign_07'=> $faker->word,
      'date_08'=>$faker->date,
      'time_08'=>$faker->time,
      'progress_08'=> $faker->word,
      'staff_name_08'=> $faker->word,
      'sign_08'=> $faker->word,
      'date_09'=>$faker->date,
      'time_09'=>$faker->time,
      'progress_09'=> $faker->word,
      'staff_name_09'=> $faker->word,
      'sign_09'=> $faker->word,
      'date_10'=>$faker->date,
      'time_10'=>$faker->time,
      'progress_10'=> $faker->word,
      'staff_name_10'=> $faker->word,
      'sign_10'=> $faker->word,
      'date_11'=>$faker->date,
      'time_11'=>$faker->time,
      'progress_11'=> $faker->word,
      'staff_name_11'=> $faker->word,
      'sign_11'=> $faker->word,
      'date_12'=>$faker->date,
      'time_12'=>$faker->time,
      'progress_12'=> $faker->word,
      'staff_name_12'=> $faker->word,
      'sign_12'=> $faker->word,
      'date_13'=>$faker->date,
      'time_13'=>$faker->time,
      'progress_13'=> $faker->word,
      'staff_name_13'=> $faker->word,
      'sign_13'=> $faker->word,
      'date_14'=>$faker->date,
      'time_14'=>$faker->time,
      'progress_14'=> $faker->word,
      'staff_name_14'=> $faker->word,
      'sign_14'=> $faker->word,
      'date_15'=>$faker->date,
      'time_15'=>$faker->time,
      'progress_15'=> $faker->word,
      'staff_name_15'=> $faker->word,
      'sign_15'=> $faker->word,
      'date_16'=>$faker->date,
      'time_16'=>$faker->time,
      'progress_16'=> $faker->word,
      'staff_name_16'=> $faker->word,
      'sign_16'=> $faker->word,
      'date_17'=>$faker->date,
      'time_17'=>$faker->time,
      'progress_17'=> $faker->word,
      'staff_name_17'=> $faker->word,
      'sign_17'=> $faker->word,
      'date_18'=>$faker->date,
      'time_18'=>$faker->time,
      'progress_18'=> $faker->word,
      'staff_name_18'=> $faker->word,
      'sign_18'=> $faker->word,
      'date_19'=>$faker->date,
      'time_19'=>$faker->time,
      'progress_19'=> $faker->word,
      'staff_name_19'=> $faker->word,
      'sign_19'=> $faker->word,
      'date_20'=>$faker->date,
      'time_20'=>$faker->time,
      'progress_20'=> $faker->word,
      'staff_name_20'=> $faker->word,
      'sign_20'=> $faker->word,
      'date_21'=>$faker->date,
      'time_21'=>$faker->time,
      'progress_21'=> $faker->word,
      'staff_name_21'=> $faker->word,
      'sign_21'=> $faker->word




    ];
});
