<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ERObservation extends Model
{
  protected $table='erobservation';

  protected $fillable = [
    'date',
    'triage_category',
    'diagnosis',
    'investigation',
    'time_01',
    'time_02',
    'time_03',
    'pulse_01',
    'pulse_02',
    'pulse_03',
    'bp_01',
    'bp_02',
    'bp_03',
    'spo2_01',
    'spo2_02',
    'spo2_03',
    'rr_01',
    'rr_02',
    'rr_03',
    'gcs_01',
    'gcs_02',
    'gcs_03',
    'temp_01',
    'temp_02',
    'temp_03',
    'iv_infusion_01',
    'qty_01',
    'time_start_01',
    'time_end_01',
    'remarks_01',
    'iv_infusion_02',
    'qty_02',
    'time_start_02',
    'time_end_02',
    'remarks_02',
    'iv_infusion_03',
    'qty_03',
    'time_start_03',
    'time_end_03',
    'remarks_03',
    'iv_infusion_04',
    'qty_04',
    'time_start_04',
    'time_end_04',
    'remarks_04',
    'name_drug_01',
    'dosage_01',
    'routine_01',
    'administration_by_01',
    'medication_time_01',
    'name_drug_02',
    'dosage_02',
    'routine_02',
    'administration_by_02',
    'medication_time_02',
    'name_drug_03',
    'dosage_03',
    'routine_03',
    'administration_by_03',
    'medication_time_03',
    'name_drug_04',
    'dosage_04',
    'routine_04',
    'administration_by_04',
    'medication_time_04',
    'name_drug_05',
    'dosage_05',
    'routine_05',
    'administration_by_05',
    'medication_time_05',
    'patient_shifted_to',
    'er_nurse',
  ];
}
